app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 5s

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  database:
    check-time-minutes: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

client:
  bot:
    base-url: http://localhost:8090
  github:
    base-url:
    token: ${GITHUB_TOKEN:}
  stackoverflow:
    base-url:
    access-token: ${STACKOVERFLOW_ACCESS_TOKEN:}
    key: ${STACKOVERFLOW_KEY:}
