app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 5s
  database-access-type: jpa

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  database:
    check-time-minutes: 0
    limit: 10
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
      - rate-limit-bucket
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=3600s

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

client:
  bot:
    base-url: http://localhost:8090
  github:
    base-url:
    token: ${GITHUB_TOKEN:}
  stackoverflow:
    base-url:
    access-token: ${STACKOVERFLOW_ACCESS_TOKEN:}
    key: ${STACKOVERFLOW_KEY:}

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-bucket
      url: .*
      http-status-code: too_many_requests
      http-response-headers:
        Content-Type: "application/json; charset=utf-8"
      http-response-body: |
        {
          "description": "Превышено количество запросов с текущего IP",
          "code": 429,
          "exceptionName": "aboba",
          "exceptionMessage": "Вы <b>превысили</b> количество доступных запросов, попробуйте чуть позже. <b>Имейте совесть</b>, не нагружайте сервер по полной"
        }
      rate-limits:
        - bandwidths:
            - capacity: 1000
              time: 30
              unit: minutes
              refill-speed: interval
          skip-condition: 
          cache-key: getRemoteAddr()
